name: Feature Toggle Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Environment Variable
        run: echo "FEATURE_NEW_FEATURE=true" >> $GITHUB_ENV

      - name: Run Tests
        run: |
          javac Main.java
          java Main
